### ISSUE TITLE
Container image overview page

### ISSUE THREAD

**Issue by Gkrumbach07** [Gkrumbach07/thoth-search#51]
**Is your feature request related to a problem? Please describe.**
related to https://github.com/thoth-station/user-api/issues/1619
> a (clickable) link to a view in Thoth Search UI (CC @Gkrumbach07) that shows additional information about container images in a human-readable and easily consumable form (ex. a listing of RPM packages, ABI present, Python interpreter version available, ...)
... see package-extract JSON document for a full listing of available metadata

**High-level Goals**
- A new page separate from the package search and advise search
- Follow the same format of main header and metric cards as the other pages
- Have its own endpoint in search `/search/image/{image_id}`

**Describe the solution you'd like**
A new page that can be linked to that displays all relevant information about a container image. It should be linked to whenever it is mentioned. 

**Acceptance Criteria**
- [x] new page with url endpoints working
- [x] a header with name and other basic information
- [x] possibly metric cards if there is enough data
- [x] add thoth container image list to home page

**Comment by Gkrumbach07** [comment]
@fridex Do you think there is enough data available to make metric cards as seen with other thoth search pages?

**Comment by fridex** [comment]
I think the stage environment should be good - there are package-extract documents available. We should sync them to prod as well.
