### ISSUE TITLE
Pressing enter on search does not work

### ISSUE THREAD

**Issue by Gkrumbach07** [Gkrumbach07/thoth-search#52]
**Describe the bug**
On the home page, if you press enter after typing out a search, it will refresh the page instead of navigating.

**To Reproduce**
1. Go to homepage
2. Type query
3. Press ENTER key

**Expected behavior**
To navigate to the next page as if you pressed the button.

**Comment by codificat** [comment]
The bot missed the previous comment, trying again:
/priority important-soon
/assign @Gkrumbach07
/triage accepted
