### ISSUE TITLE
Organize stack trace / justifications

### ISSUE THREAD

**Issue by Gkrumbach07** [Gkrumbach07/thoth-search#53]
**Is your feature request related to a problem? Please describe.**
As a Thoth search user, I expect data displayed in a readable way. In the Advise details tab, in the justifications card, all justifications are displayed in a list which is hard to read.

**High-level Goals**
Organize the justifications into either there own separate cards or into some other organized fashion. Try to include as much of the data as possible in as little space as possible

**Describe the solution you'd like**
Either new cards apart from justifications or as tags/banners in the header of the package.

**Describe alternatives you've considered**
Don't display info justifications

**Additional context**
![image](https://user-images.githubusercontent.com/12587674/151007939-5281906c-43ca-43fd-bf94-9c76d1407d70.png)

**Acceptance Criteria**

- [x] list is not longer visible
- [x] data is all being displayed somewhere
- [x] scorecards info in their own card
- [x] group items in the UI (ex. links to GitHub, …)
- [x] group items in the justification based on URL and see if that clustering will visualize justifications better

**Comment by codificat** [comment]
The bot missed the previous comment, trying again:
/triage accepted
/priority backlog
/assign @Gkrumbach07

**Comment by Gkrumbach07** [comment]
/close
list of justifications is grouped and cleaned up
