### ISSUE TITLE
Add help help icons to confusing metrics

### ISSUE THREAD

**Issue by Gkrumbach07** [Gkrumbach07/thoth-search#54]
**Is your feature request related to a problem? Please describe.**
As a new Thoth user, I am confused on what certain metrics mean or what certain acronyms mean.

**High-level Goals**
Add question mark icons that display text to describe confusing sections.

**Describe the solution you'd like**
A component that can be inserted anywhere easily.

**Describe alternatives you've considered**
Rewording or adding text to metrics that are confusing.

**Additional context**
![image](https://user-images.githubusercontent.com/12587674/151008711-893a4943-35c3-4833-b457-4401ec48fdc3.png)

**Acceptance Criteria**

- [ ] A help/tip component that can be placed anywhere
- [ ] Add the tips to confusing parts of app

**Comment by codificat** [comment]
The bot missed the previous comment, trying again:
/triage accepted
/priority backlog
/assign @Gkrumbach07
