### ISSUE TITLE
Support for multiple runtime environments

### ISSUE THREAD

**Issue by Gkrumbach07** [Gkrumbach07/thoth-search#64]
**Is your feature request related to a problem? Please describe.**
As a data scientist, I want to be able to visualize multiple runtime environments in my advise report so I can see what differences they have.

**High-level Goals**

~~Can run an advise with multiple runtime envs~~
- [x] can visualize an advise with multiple runtim envs

**Describe the solution you'd like**
I want to be able to switch between different runtime envs with a dropdown and also have an option to compare their differences.

**Describe alternatives you've considered**
Only show one env

**Acceptance Criteria**

- [x] ~~new form options to add _x_ many runtime environments~~ local history instead (see comment)
- [x] a dropdown to switch between which report to look at (might need to refactor how old and new envs work)
- [x] A way to see old reports and go to them - from home page
- [x] OPTIONAL -  a way to add reports to a compare screen. (make this dynamic so it can be any two including the old lockfile)

**Comment by Gkrumbach07** [comment]
Hi, currently Thoth Adviser only allows for one runtime environment per Adviser run. However, I a single user could have the ability to go back to recent advisor runs using the browsers local storage.

related: https://github.com/thoth-station/adviser/issues/1533

**Comment by codificat** [comment]
/remove-priority backlog
(unfortunately, this type of de-duplication has to be done manually)

**Comment by Gkrumbach07** [comment]
closing issue. User can now compare different advise reports on a new compare screen. Thoth currently only allows one runtime environment at a time, so there is no feature allowing to create a run with multiple
