### ISSUE TITLE
Have support for multiple Advise software stacks

### ISSUE THREAD

**Issue by Gkrumbach07** [Gkrumbach07/thoth-search#65]
**Is your feature request related to a problem? Please describe.**
As a super user of Thoth, I want to be able to run an advise from the UI with a `count` more than 1, so that I can pick from multiple returned software stacks.

This feature depends on the resolution of https://github.com/thoth-station/user-api/issues/1726.

**High-level Goals**
Add a count field tp the home page advise params, and add a way to see multiple advise reports and their differences.

**Describe the solution you'd like**
I want to be able to see the top advise results in a comparative way so I can pick a favorite.

**Describe alternatives you've considered**
Not possible in the UI

**Acceptance Criteria**
~~new param for `count` in the advise creation form~~ _n/a_
- [x] a way to switch and compare between advise reports.

**Comment by codificat** [comment]
related: https://github.com/thoth-station/user-api/issues/1726

/triage accepted
/priority backlog
/sig user-experience

**Comment by Gkrumbach07** [comment]
count was removed, so this issue is no longer possible. You can still switch between advise reports though.
