### ISSUE TITLE
[2pt] Direct / Root dependency counts swapped

### ISSUE THREAD

**Issue by codificat** [Gkrumbach07/thoth-search#83]
**Describe the bug**

It seems that the numbers for *Direct* and *Root* depencencies in the summary are reversed, i.e. *Root* is showing the number of *direct* dependencies, while *Direct* is showing the number of *root* level dependencies.

**To Reproduce**
1. Have a `Pipfile` with a single dependency on it, `nltk`
2. Request a stack advise
3. Check the advise results in the search UI
4. Notice that the *Dependencies Summary* box shows wrong numbers

**Expected behavior**

There should be only 1 *root* package (`nltk`) and 4 *direct* (`nltk`'s dependencies).

**Screenshots**

![imatge](https://user-images.githubusercontent.com/709574/170041639-feb0921f-a095-484d-867b-bc705f1b583d.png)

**Additional context**

Here is the advise I looked at: https://thoth-station.ninja/search/advise/adviser-220524121408-dc0af1f4d2307c27/summary

**Comment by Gkrumbach07** [comment]
These metrics will be removed in a future update that better represents what the user wants to see. We will make sure to fix this issue when that happens.

/sig user-experience
/kind bug
/priority backlog

**Comment by Gkrumbach07** [comment]
**Acceptance criteria**

- [x] Root and Direct dependencies are correctly set
- [x] Use the provided edges and nodes in the adviser document to find root and direct dependencies

/triage accepted
