### ISSUE TITLE
Compare tab improvements

### ISSUE THREAD

**Issue by TomasTomecek** [Gkrumbach07/thoth-search#95]
**Is your feature request related to a problem? Please describe.**
Just a list of things I'd improve in the output:
* Drop down where I pick from the past advises: please show a real date or some meaningful information, IDs are hard to process by humans, e.g.
  * `adviser-220712133932-7d4aebd09e248cca` - yuck
  * `2022-07-12T13:39:47 security, RHEL-8.5 (Python 3.8.8)` - I get that
* Reorder sections: I personally don't care about internals, I care about the actual results: "Stack info" should be up, "Arguments" down
* `-`, `+`, `~` - it took some time to understand the output. Mostly because I'm used to associating colors with the diff output: lines starting with `+` should be green, `-` red, `~` yellow

With these simple improvements, I'd say the Compare tab would be even more useful.

**Comment by Gkrumbach07** [comment]
**Acceptance Criteria**
- [x] Use a friendly name in the drop down 
- [x] add color to the changed/added/removed lines
- [x] prioritize stack info and justifications at the top or make a way to junk to specific sections
- [x] add a way to link to a specific comparison i.e. '/compare/advise-###-####'
- [x] Add toggle switch to only see differences

/triage accepted

**Comment by harshad16** [comment]
Story point: 5pt
/assign @Gkrumbach07
