### ISSUE TITLE
improve discover-ability by adding links to docs

### ISSUE THREAD

**Issue by goern** [Gkrumbach07/thoth-search#96]
**Is your feature request related to a problem? Please describe.**
add links to upstream docs, for example for "Package is maintained according to Security Scorecards"

**High-level Goals**
improve the understandability of the information we provide.

**Describe the solution you'd like**
add ahref

**Describe alternatives you've considered**
none

**Additional context**
n/a

**Acceptance Criteria**
- [ ] link is clickable on search WUI

**Comment by KPostOffice** [comment]
Can you specify where you want links added?

**Comment by Gkrumbach07** [comment]
@goern this should already be available. There are link buttons on the top right of cards (almost all cards). Is this still an issue?
